name: tag_and_deploy

on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:

env:
  APPLICATION_NAME: soccer_pl_tagging

jobs:
  tag_and_release:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: "0"

      - name: "Git: Configure local settings"
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: "Setup: Calculate next version number"
        uses: mathieudutour/github-tag-action@v4.1
        id: version
        with:
          tag_prefix: "v"
          dry_run: true
          default_bump: patch
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Changelog: Create full changelog for commit"
        uses: nuuday/github-changelog-action@master
        with:
          filename: CHANGELOG.md
          next_version: ${{ steps.version.outputs.new_version }}

      - name: "Git: Commit changed files and tag release"
        run: |
          git add CHANGELOG.md
          git commit -m "Changelog updated" CHANGELOG.md
          git tag -m "$Tagged new version: ${{ steps.version.outputs.new_version }}" -fa ${{ steps.version.outputs.new_tag }}
          git push --tags

      - name: "Changelog: Create changelog for release"
        uses: nuuday/github-changelog-action@master
        id: changelog
        with:
          filename: CHANGELOG.md
          next_version: ${{ steps.version.outputs.new_version }}

      - name: "Github: Create release"
        uses: actions/create-release@v1
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.new_tag }}
          release_name: Release ${{ steps.version.outputs.new_version }}
          draft: false
          prerelease: false
          body: ${{ steps.changelog.outputs.changelog }}
  build_and_push:
    runs-on: ubuntu-latest
    needs: [tag_and_release]
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Set docker name
        id: vars
        run: echo ::set-output name=docker_name::docker.pkg.github.com/${{ github.repository }}/${APPLICATION_NAME}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.vars.outputs.docker_name }}:${{needs.tag_and_release.outputs.release_tag}}
      - name: Log into registry again
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Retag to latest
        run: |
          docker pull ${{ steps.vars.outputs.docker_name }}:${{needs.tag_and_release.outputs.release_tag}}
          docker tag ${{ steps.vars.outputs.docker_name }}:${{needs.tag_and_release.outputs.release_tag}} ${{ steps.vars.outputs.docker_name }}:latest
          docker push ${{ steps.vars.outputs.docker_name }}:latest
